<h2>Last FM</h2>

<div>
    {foreach $recenttracks->track as $t}
    <div>
        {if $t->image !=''}<a href="{$t->url}" target="_blank"><img src="{$t->image[0]}" alt="{$t->artist} - {$t->name}" width="34px" height="34px" /></a>{/if}
        {$t->artist} - <a href="{$t->url}" target="_blank">{$t->name}</a>
        <br/>
        <span>{$t->date}</span>
    </div>
    {/foreach}
    <a href="http://www.last.fm/user/{$user}" target="_blank">... více zde</a>
</div>
